name: Build Node.js EXE

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Versión actualizada

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install pkg
      run: npm install -g pkg

    - name: Build EXE
      run: pkg server.js --targets node18-win-x64 --output mi-servidor.exe

    - name: Upload EXE
      uses: actions/upload-artifact@v4  # Versión actualizada aquí
      with:
        name: mi-servidor-node
        path: mi-servidor.exe
