name: Build Node.js EXE

on: [push]  # Se ejecuta cada vez que haces push

jobs:
  build:
    runs-on: ubuntu-latest  # Usa un servidor Linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Descarga tu código

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Usa Node.js 20 (ajusta si necesitas otra versión)

    - name: Install pkg (compilador)
      run: npm install -g pkg  # Instala el compilador

    - name: Build EXE
      run: pkg server.js --targets node20-win-x64 --output mi-servidor.exe  # Crea el .exe

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: mi-servidor-node
        path: mi-servidor.exe  # Guarda el .exe como descargable
